spring:
    gateway:
      routes:
        - id: produit-service
          uri: lb://produit-service
          predicates:
            - "Path=/produit/**"
        - id: client-service
          uri: lb://client-service
          predicates:
            - "Path=/client/**"
        - id: facture-service
          uri: lb://facture-service
          predicates :
            - "Path=/facture/**"
        - id: reglement-service
          uri: lb://reglement-service
          predicates :
            - "Path=/reglement/**"
        - id: stock-service
          uri: lb://stock-service
          predicates :
            - "Path=/stock/**"
            
server:
  port: 8081