eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
spring:
  boot:
    admin:
      client:
        url: http://localhost:5000
        instance:
          service-host-type: ip
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      database: gestion-produit
      host: localhost
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always